<section class="hero-post">
  <div class="container-fluid h-100">
    <div class="row h-100">
      <div class="col-12 h-100">
        <div class="content-wrapper h-100">
          <div class="image">
            <img src="{{ image }}" alt="{{ title }}" class="object-fit-cover w-100 h-100">
          </div>

          <div class="content h-100">
            <div class="content-wrapper h-100">
              <div class="container h-100">
                <div class="row h-100">
                  <div class="col-12 d-flex justify-content-center align-items-center">
                    <h2 class="display-5">{{ title }}</h2>
                  </div>
                </div>
              </div>
           </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>